import { lazy, Suspense, useEffect, useRef, useState } from "react";
import { ArrowUpRight, Move3d, Sparkles } from "lucide-react";
import { techOrbit } from "@/data/content";

const ThreeEcosystem = lazy(() => import("./ThreeEcosystem"));

export function DigitalOrb({ compact = false }: { compact?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const [pointer, setPointer] = useState({ x: 0, y: 0 });
  useEffect(() => { const node = ref.current; if (!node) return; const move = (event: PointerEvent) => { const rect = node.getBoundingClientRect(); setPointer({ x: ((event.clientX - rect.left) / rect.width - 0.5) * 2, y: ((event.clientY - rect.top) / rect.height - 0.5) * 2 }); }; node.addEventListener("pointermove", move); return () => node.removeEventListener("pointermove", move); }, []);
  return <div ref={ref} className={`orb-scene ${compact ? "orb-scene--compact" : ""}`} aria-label="Interactive Three.js digital ecosystem visual"><div className="orb-canvas"><Suspense fallback={null}><ThreeEcosystem /></Suspense></div><div className="orb-grid" /><div className="orb-glow" style={{ transform: `translate(${pointer.x * 18}px, ${pointer.y * 18}px)` }} /><div className="orb-core" style={{ transform: `rotateX(${pointer.y * -8}deg) rotateY(${pointer.x * 12}deg)` }}><div className="orb-ring orb-ring--one" /><div className="orb-ring orb-ring--two" /><div className="orb-ring orb-ring--three" /><div className="orb-center"><span>R</span></div>{techOrbit.slice(0, compact ? 5 : 8).map((tech, index) => <span key={tech} className={`orb-node orb-node--${index + 1}`}>{tech}</span>)}</div><div className="orb-caption"><Move3d size={14} /> move through the system</div></div>;
}

export function ServiceVisual({ kind, accent }: { kind: string; accent: string }) { return <div className="service-visual" style={{ "--service-accent": accent } as React.CSSProperties}><div className={`service-visual__shape service-visual__shape--${kind}`}>{kind === "web" && <><div className="mini-browser"><div className="mini-browser__bar"><i /><i /><i /></div><div className="mini-browser__body"><b /><span /><span /><em /></div></div><div className="mini-cursor">↗</div></>}{kind === "app" && <div className="mini-phone"><div className="mini-phone__notch" /><div className="mini-phone__screen"><span /><b /><i /><i /><i /></div></div>}{kind === "growth" && <><div className="growth-bars"><i /><i /><i /><i /><i /></div><div className="growth-line">↗</div></>}{kind === "ar" && <><div className="ar-cube"><span /><span /><span /></div><Sparkles className="ar-spark" /></>}{kind === "model" && <><div className="model-knot" /><div className="model-shadow" /></>}{kind === "ux" && <><div className="ux-card ux-card--a" /><div className="ux-card ux-card--b" /><div className="ux-card ux-card--c" /></>}</div><div className="service-visual__grid" /></div>; }

export function ProcessRail() { const steps = ["Challenge", "Strategy", "Design", "Technology", "Launch", "Growth"]; const [active, setActive] = useState(2); return <div className="process-rail"><div className="process-line" style={{ width: `${(active / (steps.length - 1)) * 100}%` }} />{steps.map((step, index) => <button key={step} className={`process-step ${index === active ? "is-active" : ""}`} onClick={() => setActive(index)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></button>)}<div className="process-note"><span>Current focus</span><strong>{steps[active]}</strong><ArrowUpRight size={16} /></div></div>; }

export function TechConstellation() { const [active, setActive] = useState(0); return <div className="tech-constellation"><div className="tech-constellation__center"><span>R</span><small>connected by intent</small></div>{techOrbit.map((tech, index) => { const angle = (index / techOrbit.length) * Math.PI * 2 - Math.PI / 2; const radius = 37; return <button key={tech} className={`tech-pill tech-pill--${index} ${active === index ? "is-active" : ""}`} style={{ left: `${50 + Math.cos(angle) * radius}%`, top: `${50 + Math.sin(angle) * radius}%` }} onClick={() => setActive(index)}>{tech}</button>; })}<div className="tech-constellation__detail"><span>Selected layer</span><strong>{techOrbit[active]}</strong><p>Chosen for the context, not the trend.</p></div></div>; }
