import { FormEvent, useState } from "react";
import { ArrowRight, Check, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

function Field({ label, name, type = "text", placeholder, value, onChange, required = true }: { label: string; name: string; type?: string; placeholder: string; value: string; onChange: (value: string) => void; required?: boolean }) {
  return <label className="field"><span>{label}{required && <i> *</i>}</span><input name={name} type={type} required={required} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} /></label>;
}

export function ContactForm() {
  const mutation = trpc.leads.contact.useMutation();
  const [sent, setSent] = useState(false); const [form, setForm] = useState({ name: "", email: "", phone: "", company: "", requirement: "", message: "" });
  const update = (key: keyof typeof form) => (value: string) => setForm(v => ({ ...v, [key]: value }));
  const submit = (e: FormEvent) => { e.preventDefault(); mutation.mutate(form, { onSuccess: () => { setSent(true); toast.success("Message received. We will be in touch shortly."); }, onError: (error) => toast.error(error.message) }); };
  if (sent) return <div className="form-success"><span className="success-icon"><Check /></span><span className="eyebrow">Received</span><h3>Good things start with a conversation.</h3><p>Our team will review your note and get back to you within one working day.</p></div>;
  return <form className="lead-form" onSubmit={submit}><div className="form-row"><Field label="Your name" name="name" placeholder="Jane Smith" value={form.name} onChange={update("name")} /><Field label="Work email" name="email" type="email" placeholder="jane@company.com" value={form.email} onChange={update("email")} /></div><div className="form-row"><Field label="Phone" name="phone" placeholder="+91 98765 43210" value={form.phone} onChange={update("phone")} required={false} /><Field label="Company" name="company" placeholder="Your company" value={form.company} onChange={update("company")} required={false} /></div><label className="field"><span>What can we help with? *</span><select required value={form.requirement} onChange={e => update("requirement")(e.target.value)}><option value="">Choose a focus</option><option>New website or platform</option><option>Product or app build</option><option>Brand and digital strategy</option><option>Growth and marketing</option><option>Something else</option></select></label><label className="field"><span>Tell us a little more *</span><textarea name="message" required rows={5} placeholder="What are you trying to change or unlock?" value={form.message} onChange={e => update("message")(e.target.value)} /></label><button className="button button--gold" type="submit" disabled={mutation.isPending}>{mutation.isPending ? <Loader2 className="spin" size={17} /> : <ArrowRight size={17} />} {mutation.isPending ? "Sending..." : "Send enquiry"}</button></form>;
}

export function ConsultationForm() {
  const mutation = trpc.leads.consultation.useMutation();
  const [done, setDone] = useState(false); const [form, setForm] = useState({ name: "", email: "", company: "", phone: "", focus: "" });
  const update = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm(v => ({ ...v, [key]: e.target.value }));
  if (done) return <div className="form-success"><span className="success-icon"><Check /></span><span className="eyebrow">Consultation requested</span><h3>We’ll bring the right questions.</h3><p>Expect a response from the Riyadvi team shortly.</p></div>;
  return <form className="lead-form" onSubmit={e => { e.preventDefault(); mutation.mutate(form, { onSuccess: () => { setDone(true); toast.success("Consultation request sent."); }, onError: err => toast.error(err.message) }); }}><div className="form-row"><Field label="Your name" name="name" placeholder="Jane Smith" value={form.name} onChange={v => setForm(f => ({ ...f, name: v }))} /><Field label="Work email" name="email" type="email" placeholder="jane@company.com" value={form.email} onChange={v => setForm(f => ({ ...f, email: v }))} /></div><div className="form-row"><Field label="Company" name="company" placeholder="Your company" value={form.company} onChange={v => setForm(f => ({ ...f, company: v }))} /><Field label="Phone" name="phone" placeholder="+91 98765 43210" value={form.phone} onChange={v => setForm(f => ({ ...f, phone: v }))} required={false} /></div><label className="field"><span>What would you like to explore? *</span><select required value={form.focus} onChange={update("focus")}><option value="">Select a focus</option><option>Digital transformation</option><option>New product or website</option><option>Growth opportunity</option><option>Team or technology challenge</option></select></label><button className="button button--gold" disabled={mutation.isPending}>{mutation.isPending ? "Booking..." : "Book a free consultation"}<ArrowRight size={17} /></button></form>;
}

export function HealthCheckupForm() {
  const mutation = trpc.leads.healthCheckup.useMutation(); const [step, setStep] = useState(0); const [done, setDone] = useState(false);
  const [form, setForm] = useState({ name: "", company: "", email: "", website: "", stage: "", marketing: "", technology: "", challenge: "" });
  const steps = ["Business", "Presence", "Marketing", "Technology", "Challenge"];
  const update = (key: keyof typeof form) => (value: string) => setForm(v => ({ ...v, [key]: value }));
  if (done) return <div className="form-success form-success--large"><span className="success-icon"><Check /></span><span className="eyebrow">Assessment submitted</span><h3>Your next stage starts with a clearer picture.</h3><p>We’ll review your answers and send a practical set of observations to {form.email}.</p></div>;
  const configs = [
    <><Field label="Your name" name="name" placeholder="Jane Smith" value={form.name} onChange={update("name")} /><Field label="Company" name="company" placeholder="Your company" value={form.company} onChange={update("company")} /><Field label="Work email" name="email" type="email" placeholder="jane@company.com" value={form.email} onChange={update("email")} /></>,
    <><Field label="Website" name="website" placeholder="https://yourcompany.com" value={form.website} onChange={update("website")} required={false} /><label className="field"><span>Where are you today? *</span><select required value={form.stage} onChange={e => update("stage")(e.target.value)}><option value="">Select one</option><option>Early stage</option><option>Growing steadily</option><option>Scaling quickly</option><option>Established business</option></select></label></>,
    <label className="field"><span>How would you describe your marketing? *</span><select required value={form.marketing} onChange={e => update("marketing")(e.target.value)}><option value="">Select one</option><option>We are just getting started</option><option>Some channels work, but it is inconsistent</option><option>We have a team and want to scale</option><option>We need clearer measurement</option></select></label>,
    <label className="field"><span>What is your biggest technology need? *</span><select required value={form.technology} onChange={e => update("technology")(e.target.value)}><option value="">Select one</option><option>Modernise our website</option><option>Build a digital product</option><option>Connect our systems</option><option>Improve performance and visibility</option></select></label>,
    <label className="field"><span>What would unlock the most growth right now? *</span><textarea required rows={6} placeholder="Share the challenge in your own words" value={form.challenge} onChange={e => update("challenge")(e.target.value)} /></label>,
  ];
  return <form className="health-form" onSubmit={e => { e.preventDefault(); if (step < steps.length - 1) setStep(step + 1); else mutation.mutate(form, { onSuccess: () => { setDone(true); toast.success("Health checkup received."); }, onError: err => toast.error(err.message) }); }}><div className="health-progress"><div className="health-progress__bar" style={{ width: `${((step + 1) / steps.length) * 100}%` }} /><div><span>0{step + 1} / 0{steps.length}</span><strong>{steps[step]}</strong></div></div><div className="health-fields">{configs[step]}</div><div className="health-actions">{step > 0 && <button type="button" className="text-button" onClick={() => setStep(step - 1)}>Back</button>}<button className="button button--gold" disabled={mutation.isPending}>{step === steps.length - 1 ? (mutation.isPending ? "Submitting..." : "Submit assessment") : "Continue"}<ArrowRight size={17} /></button></div></form>;
}

export function LeadMagnetForm() {
  const mutation = trpc.leads.leadMagnet.useMutation(); const [done, setDone] = useState(false); const [form, setForm] = useState({ name: "", company: "", email: "", phone: "" });
  const update = (key: keyof typeof form) => (value: string) => setForm(v => ({ ...v, [key]: value }));
  if (done) return <div className="form-success"><span className="success-icon"><Check /></span><span className="eyebrow">Your guide is ready</span><h3>Build with more confidence.</h3><p>The Software Project Planning Guide is ready to explore. Start with the questions that matter before you start building.</p><button className="button button--gold" onClick={() => toast.info("Guide access is prepared for the next release.")}>Access the guide <ArrowRight size={17} /></button></div>;
  return <form className="lead-form" onSubmit={e => { e.preventDefault(); mutation.mutate(form, { onSuccess: () => { setDone(true); toast.success("Guide access confirmed."); }, onError: err => toast.error(err.message) }); }}><Field label="Your name" name="name" placeholder="Jane Smith" value={form.name} onChange={update("name")} /><Field label="Company" name="company" placeholder="Your company" value={form.company} onChange={update("company")} /><Field label="Work email" name="email" type="email" placeholder="jane@company.com" value={form.email} onChange={update("email")} /><Field label="Phone" name="phone" placeholder="+91 98765 43210" value={form.phone} onChange={update("phone")} required={false} /><button className="button button--gold" disabled={mutation.isPending}>{mutation.isPending ? "Preparing..." : "Get the free guide"}<ArrowRight size={17} /></button></form>;
}
